
//multilang
export const SWITCH_LANGUAGE = 'SWITCH_LANGUAGE';
export const LOAD_LANGUAGE_SUCCESS = 'LOAD_LANGUAGE_SUCCESS';

//
export const LOAD_CONTACTS_SUCCESS="LOAD_CONTACTS_SUCCESS";
export const LOAD_CONTACTS_REQUEST="LOAD_CONTACTS_REQUEST";
export const LOAD_CONTACTS_ERROR="LOAD_CONTACTS_ERROR";

export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";
export const UPDATE_CONTACT_ERROR = "UPDATE_CONTACT_ERROR";
export const CREATE_CONTACT_SUCCESS="CREATE_CONTACT_SUCCESS";

export const DELETE_CONTACT_SUCCESS="DELETE_CONTACT_SUCCESS";